apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: welcome-dev
resources:
- ../../base/
- namespace.yaml
patchesJson6902:
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: welcome-app
    version: v1
images:
- name: quay.io/redhatworkshops/welcome-app
  newTag: d35ad0
